version: '3'
services:

  #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: finacc
        container_name: finacc-mono
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            # - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks: 
            - dev-server
        ports: 
            - 9000:9000
        environment:
            SERVICE_NAME: finacc
            SERVICE_TAGS: dev

    # Nginx service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes: 
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - dev-server

    # PostgreSQL DB
    pgsql:
        image: postgres:9.6-alpine
        container_name: finacc-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: finacc
            POSTGRES_PASSWORD: adm1nf1nAcc
            POSTGRES_DB: finacc
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        networks: 
            - dev-server

networks:
    dev-server:
        driver: bridge