version: '3'
services:
    
  #PHP Service
    app:
        build:
        context: .
        dockerfile: Dockerfile
        image: finacc:laravel
        container_name: finacc-mono
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks: 
            - dev-server
        ports: 
            - 9000:9000
        volumes: 
            - ./:/var/www
        environment:
        SERVICE_NAME: finacc
        SERVICE_TAGS: dev

    # Nginx service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes: 
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - dev-server

networks:
    dev-server:
        driver: bridge